kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  {{- $root := . }}
  {{- range $path, $bytes := .Files.Glob "config/fluentd/*.conf" }}
  {{ base $path }}: |-
  {{- $root.Files.Get $path | nindent 4 }}
  {{- end }}

