apiVersion: apps/v1
kind: Deployment
metadata:
  name: datarouter
spec:
  replicas: 0
  selector:
    matchLabels:
      app: datarouter
      tier: app
      role: master
  template:
    metadata:
      name: datarouter
      labels:
        app: datarouter
        tier: app
        role: master
    spec:
      serviceAccountName: {{.Release.Namespace}}-sa
      volumes:      
      - name: datarouter
        persistentVolumeClaim:
          claimName: datarouter
      containers:
      - name: datarouter
        image: {{required "Data Router Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.DATAROUTER }}
        imagePullPolicy: IfNotPresent
        args:
        - java
        - -Xms128m
        {{- if (eq "Small" .Values.resourceUnit.size) }}
        - -Xmx{{.Values.resourceUnit.small.memory.max.DATAROUTER }}m
        {{- else if (eq "Medium" .Values.resourceUnit.size) }}
        - -Xmx{{.Values.resourceUnit.medium.memory.max.DATAROUTER }}m
        {{- else if (eq "Large" .Values.resourceUnit.size) }}
        - -Xmx{{.Values.resourceUnit.large.memory.max.DATAROUTER }}m
        {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
        - -Xmx{{.Values.resourceUnit.xlarge.memory.max.DATAROUTER }}m
        {{- end }}
        - -DSYSTEMi_HOME=/metricstream/SYSTEMi
        - -DJAVA_HOME=/opt/java/bin/
        - -jar
        - /metricstream/SYSTEMi/datarouter/data-router.jar
        resources:
          limits:
            {{- if (eq "Small" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.small.memory.max.DATAROUTER }}Mi
            cpu: {{ .Values.resourceUnit.small.cpu.max.DATAROUTER }}m
            {{- else if (eq "Medium" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.medium.memory.max.DATAROUTER }}Mi
            cpu: {{ .Values.resourceUnit.medium.cpu.max.DATAROUTER }}m
            {{- else if (eq "Large" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.large.memory.max.DATAROUTER }}Mi
            cpu: {{ .Values.resourceUnit.large.cpu.max.DATAROUTER }}m
            {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.xlarge.memory.max.DATAROUTER }}Mi
            cpu: {{ .Values.resourceUnit.xlarge.cpu.max.DATAROUTER }}m
            {{- end }}
        volumeMounts:
        - mountPath: /metricstream/SYSTEMi/datarouter/datarouter.properties
          name: datarouter
          subPath: datarouter.properties
        - mountPath: /metricstream/SYSTEMi/datarouter/log4j.properties
          name: datarouter
          subPath: log4j.properties
        - mountPath: /metricstream/SYSTEMi/datarouter/smc_instrumentation.json
          name: datarouter
          subPath: smc_instrumentation.json
        - mountPath: /metricstream/SYSTEMi/datarouter/logs
          name: datarouter
          subPath: logs
        securityContext:
          readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: container-registry-key
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      allowedCapabilities: null

