apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    tier: app
    role: master
spec:
  ports:
    - name: elasticsearch
      protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 0
  selector:
    matchLabels:
      app: elasticsearch
      tier: app
      role: master
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
        tier: app
        role: master
    spec:
      serviceAccountName: {{.Release.Namespace}}-sa
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch
      containers:
      - name: elasticsearch
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.ELASTICSEARCH }}
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          {{- if (eq "Small" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.small.memory.max.ELASTICSEARCH }}m
          {{- else if (eq "Medium" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.medium.memory.max.ELASTICSEARCH }}m
          {{- else if (eq "Large" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.large.memory.max.ELASTICSEARCH }}m
          {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.xlarge.memory.max.ELASTICSEARCH }}m
          {{- end }}
        - name: processors
          value: "1"
        resources:
          limits:
            {{- if (eq "Small" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.small.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.small.cpu.max.ELASTICSEARCH }}m
            {{- else if (eq "Medium" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.medium.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.medium.cpu.max.ELASTICSEARCH }}m
            {{- else if (eq "Large" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.large.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.large.cpu.max.ELASTICSEARCH }}m
            {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.xlarge.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.xlarge.cpu.max.ELASTICSEARCH }}m
            {{- end }}
        volumeMounts:
        - mountPath: /data/elasticsearch
          subPath: elasticsearch
          name: data
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: data
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          subPath: conf/logging.yml
          name: data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: conf/elasticsearch.yml
          name: data
        - mountPath: /usr/share/elasticsearch/logs
          name: data
          subPath: logs
        - mountPath: /tmp
          name: data
          subPath: tmp
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: elasticsearch
          containerPort: 9300
      imagePullSecrets:
      - name: container-registry-key
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      allowedCapabilities: null

      
